filepath: examples/bvh/change/split/female_lotus/female_lotus_seg06_low_9.4s.bvh
start_frame_idx: 0
end_frame_idx: 225
groundplane_joint: LeftAnkle
forward_perp_joint_vectors:
  - - LeftShoulder
    - RightShoulder
  - - LeftHip
    - RightHip
scale: 0.025
up: +z
