filepath: examples/bvh/change/split/female_36pose_1/female_36pose_1_seg06_low_35.0s.bvh
start_frame_idx: 0
end_frame_idx: 840
groundplane_joint: LeftAnkle
forward_perp_joint_vectors:
  - - LeftShoulder
    - RightShoulder
  - - LeftHip
    - RightHip
scale: 0.025
up: +z
