filepath: examples/bvh/change/split/female_mediation/female_mediation_seg10_low_5.5s.bvh
start_frame_idx: 0
end_frame_idx: 130
groundplane_joint: LeftAnkle
forward_perp_joint_vectors:
  - - LeftShoulder
    - RightShoulder
  - - LeftHip
    - RightHip
scale: 0.025
up: +z
