filepath: examples/bvh/change/split/female_36pose_2/female_36pose_2_seg26_low_5.3s.bvh
start_frame_idx: 0
end_frame_idx: 126
groundplane_joint: LeftAnkle
forward_perp_joint_vectors:
  - - LeftShoulder
    - RightShoulder
  - - LeftHip
    - RightHip
scale: 0.025
up: +z
