filepath: examples/bvh/change/split/male_drum_1/male_drum_1_seg01_low_8.5s.bvh
start_frame_idx: 0
end_frame_idx: 204
groundplane_joint: LeftAnkle
forward_perp_joint_vectors:
  - - LeftShoulder
    - RightShoulder
  - - LeftHip
    - RightHip
scale: 0.025
up: +z
