filepath: examples/bvh/change/split/male_mediation/male_mediation_seg02_low_5.5s.bvh
start_frame_idx: 0
end_frame_idx: 132
groundplane_joint: LeftAnkle
forward_perp_joint_vectors:
  - - LeftShoulder
    - RightShoulder
  - - LeftHip
    - RightHip
scale: 0.025
up: +z
