filepath: examples/bvh/change/split/male_pipa_2/male_pipa_2_seg01_low_22.0s.bvh
start_frame_idx: 0
end_frame_idx: 527
groundplane_joint: LeftAnkle
forward_perp_joint_vectors:
  - - LeftShoulder
    - RightShoulder
  - - LeftHip
    - RightHip
scale: 0.025
up: +z
