filepath: examples/bvh/change/male_ribbon_middle_2000_30fps.bvh
start_frame_idx: 0
end_frame_idx: 2000
groundplane_joint: LeftAnkle
forward_perp_joint_vectors:
  - - LeftShoulder
    - RightShoulder
  - - LeftHip
    - RightHip
scale: 0.025
up: +y
