filepath: examples/bvh/change/split/male_drum_1/male_drum_1_seg20_low_15.5s.bvh
start_frame_idx: 0
end_frame_idx: 371
groundplane_joint: LeftAnkle
forward_perp_joint_vectors:
  - - LeftShoulder
    - RightShoulder
  - - LeftHip
    - RightHip
scale: 0.025
up: +z
