filepath: examples/bvh/change/split/male_mediation/male_mediation_seg01_low_14.8s.bvh
start_frame_idx: 0
end_frame_idx: 354
groundplane_joint: LeftAnkle
forward_perp_joint_vectors:
  - - LeftShoulder
    - RightShoulder
  - - LeftHip
    - RightHip
scale: 0.025
up: +z
