filepath: examples/bvh/change/split/male_drum_2/male_drum_2_seg04_low_9.2s.bvh
start_frame_idx: 0
end_frame_idx: 220
groundplane_joint: LeftAnkle
forward_perp_joint_vectors:
  - - LeftShoulder
    - RightShoulder
  - - LeftHip
    - RightHip
scale: 0.025
up: +z
