filepath: examples/bvh/change/split/male_36pose_2/male_36pose_2_seg14_low_6.5s.bvh
start_frame_idx: 0
end_frame_idx: 154
groundplane_joint: LeftAnkle
forward_perp_joint_vectors:
  - - LeftShoulder
    - RightShoulder
  - - LeftHip
    - RightHip
scale: 0.025
up: +z
