filepath: examples/bvh/change/split/male_drum_1/male_drum_1_seg05_low_9.8s.bvh
start_frame_idx: 0
end_frame_idx: 235
groundplane_joint: LeftAnkle
forward_perp_joint_vectors:
  - - LeftShoulder
    - RightShoulder
  - - LeftHip
    - RightHip
scale: 0.025
up: +z
